name: ci
on: [ push, pull_request ]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: test
        run: |
          chmod 0600 $GITHUB_WORKSPACE/vendor/vendor-ios/src/test/resources/fixtures/derived-data-manager/test_rsa
          ./gradlew clean test jacocoTestReport integrationTest
          bash <(curl -s https://codecov.io/bash)
      - name: detekt
        run: |
          ./gradlew clean detektCheck || true
      - name: validateGradlePlugins
        run: |
          ./gradlew validatePlugins
  cd-release:
    runs-on: ubuntu-20.04
    needs: ci
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: little-core-labs/get-git-tag@v3.0.2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - name: assemble cli
        run: |
          ./gradlew :cli:assembleDist -PreleaseMode=RELEASE
          rm -f cli/build/distributions/marathon-*-SNAPSHOT.zip || true
      - name: deliver cli
        uses: softprops/action-gh-release@v1
        with:
          files: cli/build/distributions/marathon-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
